export const FLOWERS = [
  { emoji: '🌼', name: 'Daisy' },
  { emoji: '🌸', name: 'Blossom' },
  { emoji: '🌻', name: 'Sunflower' },
  { emoji: '🌷', name: 'Tulip' },
  { emoji: '🌺', name: 'Hibiscus' },
  { emoji: '🪷', name: 'Lotus' },
  { emoji: '💐', name: 'Bouquet' },
  { emoji: '🌹', name: 'Rose' },
  { emoji: '🏵️', name: 'Rosette' },
  { emoji: '🌾', name: 'Wheat' },
  { emoji: '🍀', name: 'Clover' },
  { emoji: '🌿', name: 'Herb' },
  { emoji: '🍃', name: 'Leaves' },
  { emoji: '🍂', name: 'Autumn Leaf' },
  { emoji: '🍁', name: 'Maple Leaf' },
  { emoji: '🌵', name: 'Cactus' },
  { emoji: '🎋', name: 'Bamboo' },
  { emoji: '🎍', name: 'Pine' },
  { emoji: '🪴', name: 'Potted Plant' },
  { emoji: '🫧', name: 'Bubbles' },
];

export const CREATURES = [
  { emoji: '🐛', name: 'Caterpillar', category: 'Insects' },
  { emoji: '🐜', name: 'Ant', category: 'Insects' },
  { emoji: '🐝', name: 'Bee', category: 'Insects' },
  { emoji: '🐞', name: 'Ladybug', category: 'Insects' },
  { emoji: '🦋', name: 'Butterfly', category: 'Insects' },
  { emoji: '🦗', name: 'Cricket', category: 'Insects' },
  { emoji: '🦟', name: 'Mosquito', category: 'Insects' },
  { emoji: '🪲', name: 'Beetle', category: 'Insects' },
  { emoji: '🕷️', name: 'Spider', category: 'Insects' },
  { emoji: '🦂', name: 'Scorpion', category: 'Insects' },
  { emoji: '🐦', name: 'Bird', category: 'Birds' },
  { emoji: '🦆', name: 'Duck', category: 'Birds' },
  { emoji: '🦅', name: 'Eagle', category: 'Birds' },
  { emoji: '🦉', name: 'Owl', category: 'Birds' },
  { emoji: '🦚', name: 'Peacock', category: 'Birds' },
  { emoji: '🦜', name: 'Parrot', category: 'Birds' },
  { emoji: '🐧', name: 'Penguin', category: 'Birds' },
  { emoji: '🦢', name: 'Swan', category: 'Birds' },
  { emoji: '🦩', name: 'Flamingo', category: 'Birds' },
  { emoji: '🐓', name: 'Rooster', category: 'Birds' },
  { emoji: '🐇', name: 'Rabbit', category: 'Animals' },
  { emoji: '🦔', name: 'Hedgehog', category: 'Animals' },
  { emoji: '🐿️', name: 'Chipmunk', category: 'Animals' },
  { emoji: '🦎', name: 'Lizard', category: 'Animals' },
  { emoji: '🐸', name: 'Frog', category: 'Animals' },
  { emoji: '🐢', name: 'Turtle', category: 'Animals' },
  { emoji: '🐹', name: 'Hamster', category: 'Animals' },
  { emoji: '🐭', name: 'Mouse', category: 'Animals' },
  { emoji: '🐱', name: 'Cat', category: 'Animals' },
  { emoji: '🦊', name: 'Fox', category: 'Animals' },
  { emoji: '🐠', name: 'Tropical Fish', category: 'Ocean' },
  { emoji: '🐙', name: 'Octopus', category: 'Ocean' },
  { emoji: '🦀', name: 'Crab', category: 'Ocean' },
  { emoji: '🐚', name: 'Shell', category: 'Ocean' },
  { emoji: '🦭', name: 'Seal', category: 'Ocean' },
  { emoji: '🐬', name: 'Dolphin', category: 'Ocean' },
  { emoji: '🦑', name: 'Squid', category: 'Ocean' },
  { emoji: '🐡', name: 'Blowfish', category: 'Ocean' },
  { emoji: '🦈', name: 'Shark', category: 'Ocean' },
  { emoji: '🪸', name: 'Coral', category: 'Ocean' },
  { emoji: '🦄', name: 'Unicorn', category: 'Magic' },
  { emoji: '🐉', name: 'Dragon', category: 'Magic' },
  { emoji: '🦕', name: 'Sauropod', category: 'Magic' },
  { emoji: '🦖', name: 'T-Rex', category: 'Magic' },
  { emoji: '🧸', name: 'Teddy Bear', category: 'Magic' },
  { emoji: '🪄', name: 'Magic Wand', category: 'Magic' },
  { emoji: '🌟', name: 'Star', category: 'Magic' },
  { emoji: '💎', name: 'Gem', category: 'Magic' },
  { emoji: '👑', name: 'Crown', category: 'Magic' },
  { emoji: '✨', name: 'Sparkles', category: 'Magic' },
];

export function getFlowerForWeek(totalFlowersCollected) {
  return FLOWERS[totalFlowersCollected % FLOWERS.length];
}

export function getCreatureIndexForFlowerCount(flowerCount) {
  if (flowerCount === 0 || flowerCount % 4 !== 0) return null;
  return (flowerCount / 4) - 1;
}

export default { FLOWERS, CREATURES, getFlowerForWeek, getCreatureIndexForFlowerCount };
